
[functions]
  node_bundler = "esbuild"

# [[redirects]]
# from = "/proxy"
# to = "/.netlify/functions/proxy"
# status = 200

[[redirects]]
  from = "/*"
  to = "https://api-free.deepl.com/:splat"
  status = 200
